# Generated by Django 4.2.4 on 2023-08-11 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fun_facts', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='datesfact',
            unique_together={('month', 'day')},
        ),
    ]
