# Generated by Django 4.2.4 on 2023-08-11 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fun_facts", "0002_alter_datesfact_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="PopularDates",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("month", models.CharField(max_length=20)),
                ("day", models.IntegerField(max_length=5)),
            ],
        ),
    ]
