# Generated by Django 4.2.4 on 2023-08-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fun_facts", "0006_alter_populardates_days_checked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datesfact",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
