# pull official base image
FROM python:3.11.4-slim-buster


# set work directory
WORKDIR /usr/src/app/

# set environment variables
ENV PYTHONUNBUFFERED 1 
ENV PYTHONDONTWRITEBYTECODE 1

# install dependencies
RUN pip install --upgrade pip
# copy project
COPY . .

RUN pip install -r requirements.txt &&\
    python manage.py collectstatic
